// GENERATED by scripts/sync-core.mjs from core/. Do not edit here.
// Original creature and postcard art as inline SVG.
// The postcard is the placeholder for Grok Imagine output.
import { hashString } from "./geo.js";

const PALETTES = [
  { sky: ["#ffd8a8", "#ffb4a2"], hills: ["#8fc97a", "#5fa052"], sun: "#fff3c4" },
  { sky: ["#bde0fe", "#a2d2ff"], hills: ["#95d5b2", "#52b788"], sun: "#ffffff" },
  { sky: ["#e0c3fc", "#ffc8dd"], hills: ["#b7e4c7", "#74c69d"], sun: "#fff0f3" },
  { sky: ["#caf0f8", "#90e0ef"], hills: ["#a7c957", "#6a994e"], sun: "#fefae0" },
];

export function creatureSvg(agent, level = 1) {
  const hat = level >= 2
    ? `<g transform="translate(32 9)">
         <circle r="4" fill="#ff8fab"/><circle cx="-5" cy="2" r="3" fill="#ffc2d1"/>
         <circle cx="5" cy="2" r="3" fill="#ffc2d1"/><circle r="2" fill="#ffe066"/>
       </g>`
    : "";
  return `
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64" role="img" aria-label="${agent.name}">
      <path d="M32 18 C30 8 22 6 20 4 C26 4 33 8 32 18" fill="${agent.leaf}"/>
      <ellipse cx="32" cy="40" rx="18" ry="20" fill="${agent.color}"/>
      <ellipse cx="32" cy="46" rx="10" ry="8" fill="#ffffff" opacity="0.25"/>
      <circle cx="25" cy="36" r="3.2" fill="#2c3a2a"/>
      <circle cx="39" cy="36" r="3.2" fill="#2c3a2a"/>
      <circle cx="26" cy="35" r="1" fill="#fff"/>
      <circle cx="40" cy="35" r="1" fill="#fff"/>
      <path d="M28 44 Q32 47 36 44" stroke="#2c3a2a" stroke-width="2" fill="none" stroke-linecap="round"/>
      <ellipse cx="22" cy="42" rx="3" ry="2" fill="#ff8a8a" opacity="0.5"/>
      <ellipse cx="42" cy="42" rx="3" ry="2" fill="#ff8a8a" opacity="0.5"/>
      ${hat}
    </svg>`;
}

export function postcardSvg(placeTitle, agent) {
  const palette = PALETTES[hashString(placeTitle) % PALETTES.length];
  return `
    <svg viewBox="0 0 400 180">
      <defs>
        <linearGradient id="sky" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="${palette.sky[0]}"/>
          <stop offset="1" stop-color="${palette.sky[1]}"/>
        </linearGradient>
      </defs>
      <rect width="400" height="180" fill="url(#sky)"/>
      <circle cx="320" cy="50" r="26" fill="${palette.sun}" opacity="0.9"/>
      <path d="M0 120 Q100 70 200 115 T400 105 V180 H0 Z" fill="${palette.hills[0]}"/>
      <path d="M0 150 Q120 110 240 145 T400 140 V180 H0 Z" fill="${palette.hills[1]}"/>
      <path d="M120 180 Q190 150 210 128" stroke="#f1e3c6" stroke-width="10" fill="none" stroke-linecap="round"/>
      <text x="200" y="166" text-anchor="middle" font-size="12" fill="#fff" font-family="system-ui">
        🌸 🌼 🌷 Wish you were here! 🌷 🌼 🌸
      </text>
      <g transform="translate(36 70) scale(1.3)">${creatureSvg(agent)}</g>
    </svg>`;
}

// Savings tree: grows through TREE_STAGES (0 = seed ... 5 = fruit tree).
export function treeSvg(stageIndex) {
  const ground = `<ellipse cx="100" cy="182" rx="80" ry="12" fill="#8d6e63"/>
    <ellipse cx="100" cy="178" rx="70" ry="8" fill="#a1887f"/>`;
  if (stageIndex === 0) {
    return svgFrame(`${ground}<ellipse cx="100" cy="172" rx="9" ry="7" fill="#795548"/>
      <path d="M100 166 q3 -6 0 -10" stroke="#66bb6a" stroke-width="2" fill="none"/>`);
  }
  if (stageIndex === 1) {
    return svgFrame(`${ground}<path d="M100 178 V150" stroke="#558b2f" stroke-width="4"/>
      <ellipse cx="90" cy="148" rx="11" ry="6" fill="#7cb342" transform="rotate(-25 90 148)"/>
      <ellipse cx="110" cy="148" rx="11" ry="6" fill="#8bc34a" transform="rotate(25 110 148)"/>`);
  }
  const trunkTop = 178 - 40 - stageIndex * 8;
  const canopy = 22 + stageIndex * 6;
  const cy = trunkTop - canopy * 0.4;
  const leaves = [
    [100, cy, canopy], [100 - canopy * 0.7, cy + canopy * 0.35, canopy * 0.7],
    [100 + canopy * 0.7, cy + canopy * 0.35, canopy * 0.7], [100, cy - canopy * 0.55, canopy * 0.65],
  ].map(([x, y, r], i) => `<circle cx="${x}" cy="${y}" r="${r}" fill="${i % 2 ? "#66bb6a" : "#4caf50"}"/>`).join("");
  const spots = [[-0.5, -0.1], [0.35, -0.35], [0.1, 0.25], [-0.2, -0.6], [0.6, 0.2], [-0.65, 0.35]];
  const decorate = (fill, r) => spots
    .map(([dx, dy]) => `<circle cx="${100 + dx * canopy}" cy="${cy + dy * canopy}" r="${r}" fill="${fill}"/>`).join("");
  const blossoms = stageIndex >= 4 ? decorate("#f8bbd0", 5) : "";
  const apples = stageIndex >= 5 ? decorate("#e53935", 6) : "";
  return svgFrame(`${ground}
    <path d="M94 178 L97 ${trunkTop} H103 L106 178 Z" fill="#795548"/>
    ${leaves}${blossoms}${apples}`);
}

function svgFrame(content) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200" role="img" aria-label="Your savings tree">
    <rect width="200" height="200" rx="16" fill="#e8f5e9"/>${content}</svg>`;
}
