// GENERATED by scripts/sync-core.mjs from core/. Do not edit here.
// Physical Sciences Building, Cornell University
export const DEFAULT_CENTER = Object.freeze({ lat: 42.45, lon: -76.4816 });
export const DEFAULT_ZOOM = 17;

export const SCOUT_RADIUS_M = 1000;
export const SCOUT_CANDIDATES = 8;
export const MIN_PLACE_DISTANCE_M = 60;

// Expeditions take real time proportional to distance, compressed for demos.
export const EXPEDITION_MS_PER_METER = 12;
export const EXPEDITION_MIN_MS = 4000;
export const EXPEDITION_MAX_MS = 15000;

export const BLOOM_EVERY_M = 12;
export const DEMO_WALK_SPEED_MPS = 25; // sped up so a demo walk takes seconds
export const WALKING_SPEED_MPS = 1.3;

export const XP_PER_LEVEL = 2;
export const FETCH_TIMEOUT_MS = 10000;

// Ranks. The web app estimates steps from distance; the mobile app reads the real pedometer.
export const STEP_LENGTH_M = 0.75;
export const POINTS = Object.freeze({ stepsPerPoint: 10, landmarkFound: 50, landmarkCaptured: 100 });

// Leaderboards are grouped by region; updated from GPS via reverse geocoding.
export const DEFAULT_REGION = Object.freeze({ local: "Ithaca", state: "New York", national: "United States" });
export const LEADERBOARD_TOP = 10;

// Capture: you must be this close to a landmark to photograph it.
export const CAPTURE_RADIUS_M = 50;
export const ALBUM_MAX_CARDS = 12;
