// GENERATED by scripts/sync-core.mjs from core/. Do not edit here.
// Today's walk: steps and places you actually passed. Shared by the phone,
// the API, and the iMessage agent. Dates use the device/local calendar day.
export const DAY_PLACE_LIMIT = 20;
export const STEP_MILESTONES = Object.freeze([1000, 2500, 5000, 10000, 15000, 20000]);

const pad = (n) => String(n).padStart(2, "0");

export function todayKey(now = new Date()) {
  return `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`;
}

export function emptyDay(date = todayKey()) {
  return { date, steps: 0, places: [] };
}

export function rollDay(day, now = new Date()) {
  const date = todayKey(now);
  if (day?.date === date && Array.isArray(day.places) && Number.isFinite(day.steps)) {
    return { date, steps: Math.max(0, Math.floor(day.steps)), places: day.places };
  }
  return emptyDay(date);
}

function placeId(place) {
  return String(place?.id ?? "").trim();
}

function placeTitle(place) {
  return String(place?.title ?? place?.name ?? "").trim().slice(0, 80);
}

export function addDaySteps(day, added, now = new Date()) {
  const next = rollDay(day, now);
  const extra = Number(added);
  if (!Number.isFinite(extra) || extra <= 0) return next;
  return { ...next, steps: next.steps + Math.floor(extra) };
}

export function addDayPlace(day, place, now = new Date()) {
  const next = rollDay(day, now);
  const id = placeId(place);
  const title = placeTitle(place);
  if (!id || !title) return next;
  if (next.places.some((p) => String(p.id) === id)) return next;
  return { ...next, places: [...next.places, { id, title }].slice(-DAY_PLACE_LIMIT) };
}

export function mergeDayLogs(current, incoming, now = new Date()) {
  const date = todayKey(now);
  const pick = (day) => (day?.date === date ? rollDay(day, now) : emptyDay(date));
  const base = pick(current);
  const other = pick(incoming);
  const byId = new Map();
  for (const place of [...base.places, ...other.places]) {
    if (!placeId(place) || !placeTitle(place)) continue;
    if (!byId.has(placeId(place))) byId.set(placeId(place), { id: placeId(place), title: placeTitle(place) });
  }
  return {
    date,
    steps: Math.max(base.steps, other.steps),
    places: [...byId.values()].slice(-DAY_PLACE_LIMIT),
  };
}

export function crossedMilestone(before, after) {
  return STEP_MILESTONES.filter((n) => before < n && after >= n);
}

export function shouldNotifyDay(prev, next) {
  if (!next) return false;
  const older = rollDay(prev, new Date(`${next.date}T12:00:00`));
  if (older.date !== next.date) return next.places.length > 0 || next.steps > 0;
  if (next.places.length > older.places.length) return true;
  return crossedMilestone(older.steps, next.steps).length > 0;
}

function formatSteps(n) {
  return String(n).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}

export function formatDayUpdate(day, now = new Date()) {
  const log = rollDay(day, now);
  const steps = formatSteps(log.steps);
  if (log.places.length === 0) {
    return `🍊 Pip: Today's tally is ${steps} steps. No landmarks logged yet — walk with the app or text "arrived" after a scout.`;
  }
  const names = log.places.map((p) => p.title).join(", ");
  return `🍊 Pip: Today's walk — ${steps} steps.\nPlaces you passed: ${names}.`;
}

export function dayFingerprint(day) {
  const log = rollDay(day);
  return `${log.date}|${log.steps}|${log.places.map((p) => p.id).join(",")}`;
}
