// GENERATED by scripts/sync-core.mjs from prototype/js. Do not edit here.
// Capital One Nessie API (mock banking sandbox): http://api.nessieisreal.com
// UNTESTED: the API was unreachable while this was written (connections reset).
// Endpoint shapes follow Nessie's documentation; confirm them at the Capital One
// table before the demo. Every caller falls back to the local ledger on failure.
import { FETCH_TIMEOUT_MS } from "./config.js";

const BASE_URL = "http://api.nessieisreal.com";
const STARTING_CHECKING_BALANCE = 500;

async function nessie(path, key, { method = "GET", body } = {}) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
  try {
    const response = await fetch(`${BASE_URL}${path}?key=${encodeURIComponent(key)}`, {
      method,
      headers: body ? { "Content-Type": "application/json" } : undefined,
      body: body ? JSON.stringify(body) : undefined,
      signal: controller.signal,
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(data.message ?? `Nessie request failed (${response.status})`);
    return data;
  } finally {
    clearTimeout(timer);
  }
}

// Create objects return { code, message, objectCreated: { _id, ... } }.
const createdId = (data) => {
  const id = data?.objectCreated?._id;
  if (!id) throw new Error("Nessie response had no id");
  return id;
};

// One-time setup: a customer with a checking account (where fares would have
// come from) and a savings account (where they go instead).
export async function setupBank(key, displayName) {
  const customerId = createdId(await nessie("/customers", key, {
    method: "POST",
    body: {
      first_name: displayName,
      last_name: "Wanderer",
      address: { street_number: "1", street_name: "Feeney Way", city: "Ithaca", state: "NY", zip: "14853" },
    },
  }));
  const account = (type, nickname, balance) => nessie(`/customers/${customerId}/accounts`, key, {
    method: "POST",
    body: { type, nickname, rewards: 0, balance },
  });
  const checkingId = createdId(await account("Checking", "Everyday", STARTING_CHECKING_BALANCE));
  const savingsId = createdId(await account("Savings", "Walking Savings", 0));
  return { customerId, checkingId, savingsId };
}

export async function transferToSavings(key, bank, amount, description) {
  const data = await nessie(`/accounts/${bank.checkingId}/transfers`, key, {
    method: "POST",
    body: {
      medium: "balance",
      payee_id: bank.savingsId,
      amount,
      transaction_date: new Date().toISOString().slice(0, 10),
      description,
    },
  });
  return createdId(data);
}

export async function getBalance(key, accountId) {
  const account = await nessie(`/accounts/${accountId}`, key);
  return account.balance;
}
