// GENERATED by scripts/sync-core.mjs from core/. Do not edit here.
// Bot rivals guarding real Cornell landmarks, so the map always has someone to
// fight. Shared by the server (virtual guards, see server/src/bots.js) and the
// phone app when it plays offline (mobile/src/components/fakeData.js).
// Each uses its landmark's Wikipedia page id, title and coordinates: the same
// id Explore and the nearby-landmarks list use, so a bot and its real place
// are one landmark on the map, and the landmark screen finds its photo.

const rival = (pageId, title, lat, lon, ownerName, pet) => ({
  landmarkId: String(pageId),
  title,
  lat,
  lon,
  ownerName,
  pet: { id: `pet-bot-${pageId}`, art: null, spaceBorn: false, ...pet },
});

export const DEMO_RIVALS = Object.freeze([
  rival(53317176, "Uris Library", 42.447778, -76.485278, "OrchidOz",
    { name: "Comet", species: "bear", rarity: "epic", petClass: "Guardian", color: "midnight", power: 48 }),
  rival(7817030, "Bailey Hall (Ithaca, New York)", 42.449028, -76.480139, "AsterAri",
    { name: "Hazel", species: "fox", rarity: "rare", petClass: "Scout", color: "golden", power: 31 }),
  rival(45680751, "Rand Hall", 42.451222, -76.482694, "SorrelSky",
    { name: "Tofu", species: "cat", rarity: "common", petClass: "Storyteller", color: "snowy", power: 18 }),
  rival(13311290, "Morrill Hall (Cornell University)", 42.448611, -76.485278, "MapleMo",
    { name: "Pebble", species: "bunny", rarity: "common", petClass: "Pathfinder", color: "rose", power: 22 }),
  rival(12957897, "Sage Chapel", 42.447211, -76.484452, "WillowWu",
    { name: "Juniper", species: "shiba", rarity: "rare", petClass: "Guardian", color: "cinnamon", power: 36 }),
  rival(7072926, "Willard Straight Hall", 42.4465, -76.4855, "CloverKai",
    { name: "Mochi", species: "husky", rarity: "common", petClass: "Scout", color: "mint", power: 15 }),
  rival(64354437, "Triphammer Falls", 42.4518, -76.4798, "RowanRay",
    { name: "Nova", species: "cat", rarity: "legendary", petClass: "Guardian", color: "golden", power: 66 }),
  rival(12986113, "Risley Residential College", 42.45307, -76.481962, "PoppyPark",
    { name: "Sprocket", species: "bear", rarity: "epic", petClass: "Pathfinder", color: "snowy", power: 44 }),
]);
