// Copies the platform-independent game logic from the web prototype into
// src/core, so the web and mobile versions share one source of truth.
// Run with: npm run sync-core   (edit the files in prototype/js, not src/core)
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, "..", "..", "prototype", "js");
const target = join(here, "..", "src", "core");

const CORE_FILES = [
  "agents.js", "art.js", "config.js", "geo.js", "leaderboard.js",
  "nessie.js", "rank.js", "savings.js", "services.js",
];

const HEADER = "// GENERATED by scripts/sync-core.mjs from prototype/js. Do not edit here.\n";

mkdirSync(target, { recursive: true });
for (const file of CORE_FILES) {
  const from = join(source, file);
  const to = join(target, file);
  copyFileSync(from, to);
  writeFileSync(to, HEADER + readFileSync(to, "utf8"));
}
console.log(`Synced ${CORE_FILES.length} core files into src/core`);
